#!/bin/bash
#
# Usage:
#    clock list        # list available timezones
#    clock TIMEZONE    # using one of the available timezones

if [ $# != 1 ]; then
    echo Usage:
    echo $0 list
    echo or
    echo $0 TIMEZONE
    exit 2
fi

if [ $1 == "list" ]; then
    timedatectl list-timezones
    exit 0
fi

TZ_LIST=$(timedatectl list-timezones --no-pager)
if [[ $TZ_LIST == *"$1"* ]]; then
    TZ=$1 date
    exit 0
fi

echo Invalid timezone specified!
echo Please use "$0 list" to see what timezones are available.
exit 1
