#!/bin/bash
curl -s -i https://git.io -F "url=$1" -F "code=$2" | grep -Fi Location

# will not return any output if short code is already taken
# https://github.com/aashutoshrathi/awesome-bashrc/issues/15
# https://blog.github.com/2011-11-10-git-io-github-url-shortener/
